name: Build and Upload ZIP Artifacts

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    tags:             # Automatically triggers if a Git tag is created
      - '*'           # Match all tags, including '1.0', 'v1.0', '2.0', etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (pnpm install)
        run: |
          mkdir packages
          pnpm install

      - name: Run application (pnpm start)
        run: pnpm start

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: built-zips
          path: packages/*.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')  # Runs only if triggered by a tag
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-zips

      - name: Get the release for the tag
        id: get_release
        uses: actions-ecosystem/action-get-release-by-tag@v1
        with:
          tag_name: ${{ github.ref_name }}

      - name: Upload built artifacts to release
        if: steps.get_release.outputs.release_id != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: packages/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # Fails silently if release already exists without breaking